import express from 'express';
import cors from 'cors';

const books = [
  {
    id: 1,
    title: "Mândrie și prejudecată",
    author: "Jane Austen",
    genre: "Romantic",
    publisher: "Penguin Classics",
    publicationYear: 1813,
    isbn: "9780141439518",
    language: "Română",
    pages: 432,
    description: "O poveste clasică despre dragoste, prejudecăți și convenții sociale.",
    coverImage: "https://via.placeholder.com/150x220?text=Mandrie+si+Prejudecata",
    rating: 4.8,
    availableCopies: 12
  },
  {
    id: 2,
    title: "Crimă și pedeapsă",
    author: "Fiodor Dostoievski",
    genre: "Clasic / Psihologic",
    publisher: "Humanitas",
    publicationYear: 1866,
    isbn: "9789735014928",
    language: "Română",
    pages: 576,
    description: "Un roman psihologic despre vină, conștiință și mântuire.",
    coverImage: "https://via.placeholder.com/150x220?text=Crima+si+Pedepasa",
    rating: 4.7,
    availableCopies: 9
  },
  {
    id: 3,
    title: "Micul Prinț",
    author: "Antoine de Saint-Exupéry",
    genre: "Poveste / Filosofic",
    publisher: "Rao",
    publicationYear: 1943,
    isbn: "9789731032056",
    language: "Română",
    pages: 96,
    description: "O poveste poetică despre inocență, prietenie și iubire.",
    coverImage: "https://via.placeholder.com/150x220?text=Micul+Print",
    rating: 4.9,
    availableCopies: 20
  },
  {
    id: 4,
    title: "1984",
    author: "George Orwell",
    genre: "Distopie",
    publisher: "Polirom",
    publicationYear: 1949,
    isbn: "9789734617991",
    language: "Română",
    pages: 328,
    description: "Un roman distopic despre supraveghere, libertate și totalitarism.",
    coverImage: "https://via.placeholder.com/150x220?text=1984",
    rating: 4.8,
    availableCopies: 14
  },
  {
    id: 5,
    title: "Mizerabilii",
    author: "Victor Hugo",
    genre: "Clasic / Dramă",
    publisher: "Litera",
    publicationYear: 1862,
    isbn: "9789736752362",
    language: "Română",
    pages: 1456,
    description: "O capodoperă despre justiție, iubire și sacrificiu.",
    coverImage: "https://via.placeholder.com/150x220?text=Mizerabilii",
    rating: 4.7,
    availableCopies: 7
  },
  {
    id: 6,
    title: "Harry Potter și Piatra Filozofală",
    author: "J.K. Rowling",
    genre: "Fantasy",
    publisher: "Arthur",
    publicationYear: 1997,
    isbn: "9786067885249",
    language: "Română",
    pages: 336,
    description: "Primul volum din faimoasa serie Harry Potter.",
    coverImage: "https://via.placeholder.com/150x220?text=Harry+Potter+1",
    rating: 4.9,
    availableCopies: 25
  },
  {
    id: 7,
    title: "Hobbitul",
    author: "J.R.R. Tolkien",
    genre: "Fantasy / Aventură",
    publisher: "Arthur",
    publicationYear: 1937,
    isbn: "9789731033244",
    language: "Română",
    pages: 310,
    description: "Aventura lui Bilbo Baggins în lumea fascinantă a Pământului de Mijloc.",
    coverImage: "https://via.placeholder.com/150x220?text=Hobbitul",
    rating: 4.8,
    availableCopies: 18
  },
  {
    id: 8,
    title: "Don Quijote",
    author: "Miguel de Cervantes",
    genre: "Clasic / Aventură",
    publisher: "Litera",
    publicationYear: 1605,
    isbn: "9789736759994",
    language: "Română",
    pages: 1056,
    description: "Povestea cavalerului rătăcitor Don Quijote și a scutierului său Sancho Panza.",
    coverImage: "https://via.placeholder.com/150x220?text=Don+Quijote",
    rating: 4.6,
    availableCopies: 10
  },
  {
    id: 9,
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Horror / Goticul",
    publisher: "Penguin",
    publicationYear: 1818,
    isbn: "9780143131846",
    language: "Română",
    pages: 288,
    description: "Roman gotic despre un om de știință care creează un monstru.",
    coverImage: "https://via.placeholder.com/150x220?text=Frankenstein",
    rating: 4.5,
    availableCopies: 11
  },
  {
    id: 10,
    title: "De veghe în lanul de secară",
    author: "J.D. Salinger",
    genre: "Ficțiune contemporană",
    publisher: "Polirom",
    publicationYear: 1951,
    isbn: "9789736818233",
    language: "Română",
    pages: 240,
    description: "Povestea celebră a lui Holden Caulfield despre adolescență și rebeliune.",
    coverImage: "https://via.placeholder.com/150x220?text=De+Veghe+in+Lanul+de+Secara",
    rating: 4.4,
    availableCopies: 13
  },
  {
    id: 11,
    title: "Anna Karenina",
    author: "Lev Tolstoi",
    genre: "Clasic / Dramă",
    publisher: "Humanitas",
    publicationYear: 1878,
    isbn: "9789735062461",
    language: "Română",
    pages: 864,
    description: "Roman despre iubire, trădare și societate în Rusia secolului XIX.",
    coverImage: "https://via.placeholder.com/150x220?text=Anna+Karenina",
    rating: 4.7,
    availableCopies: 10
  },
  {
    id: 12,
    title: "Alice în Țara Minunilor",
    author: "Lewis Carroll",
    genre: "Fantezie / Aventură",
    publisher: "Rao",
    publicationYear: 1865,
    isbn: "9789731034999",
    language: "Română",
    pages: 200,
    description: "Călătoria fantastică a lui Alice într-o lume ciudată și minunată.",
    coverImage: "https://via.placeholder.com/150x220?text=Alice+in+Tara+Minunilor",
    rating: 4.6,
    availableCopies: 15
  },
  {
    id: 13,
    title: "Castelul",
    author: "Franz Kafka",
    genre: "Ficțiune / Absurd",
    publisher: "Polirom",
    publicationYear: 1926,
    isbn: "9789734601857",
    language: "Română",
    pages: 288,
    description: "Un roman despre lupta omului împotriva birocrației și absurdului.",
    coverImage: "https://via.placeholder.com/150x220?text=Castelul",
    rating: 4.3,
    availableCopies: 9
  },
  {
    id: 14,
    title: "Lolita",
    author: "Vladimir Nabokov",
    genre: "Ficțiune controversată",
    publisher: "Polirom",
    publicationYear: 1955,
    isbn: "9789734609281",
    language: "Română",
    pages: 336,
    description: "Roman despre obsesie și moralitate, considerat clasic modern.",
    coverImage: "https://via.placeholder.com/150x220?text=Lolita",
    rating: 4.4,
    availableCopies: 11
  },
  {
    id: 15,
    title: "Cel mai iubit dintre pământeni",
    author: "Marin Preda",
    genre: "Ficțiune românească",
    publisher: "Editura Eminescu",
    publicationYear: 1980,
    isbn: "9789735901456",
    language: "Română",
    pages: 672,
    description: "Roman despre viața unui intelectual în perioada comunistă.",
    coverImage: "https://via.placeholder.com/150x220?text=Cel+mai+iubit",
    rating: 4.6,
    availableCopies: 12
  },
  {
    id: 16,
    title: "Procesul",
    author: "Franz Kafka",
    genre: "Ficțiune / Absurd",
    publisher: "Polirom",
    publicationYear: 1925,
    isbn: "9789734601840",
    language: "Română",
    pages: 256,
    description: "Un om este arestat și judecat fără să știe de ce.",
    coverImage: "https://via.placeholder.com/150x220?text=Procesul",
    rating: 4.3,
    availableCopies: 10
  },
  {
    id: 17,
    title: "Cei trei mușchetari",
    author: "Alexandre Dumas",
    genre: "Aventură / Clasic",
    publisher: "Litera",
    publicationYear: 1844,
    isbn: "9789736752249",
    language: "Română",
    pages: 688,
    description: "Aventurile lui d'Artagnan și a celor trei mușchetari în Franța secolului XVII.",
    coverImage: "https://via.placeholder.com/150x220?text=Cei+trei+Muschetari",
    rating: 4.7,
    availableCopies: 15
  },
  {
    id: 18,
    title: "Povestea slujitoarei",
    author: "Margaret Atwood",
    genre: "Distopie / Feminism",
    publisher: "Polirom",
    publicationYear: 1985,
    isbn: "9789734618302",
    language: "Română",
    pages: 336,
    description: "O societate totalitară în care femeile sunt supuse și controlate.",
    coverImage: "https://via.placeholder.com/150x220?text=Povestea+Slujitoarei",
    rating: 4.5,
    availableCopies: 13
  },
  {
    id: 19,
    title: "Jurnalul Annei Frank",
    author: "Anne Frank",
    genre: "Memorii / Istorie",
    publisher: "Humanitas",
    publicationYear: 1947,
    isbn: "9789735062300",
    language: "Română",
    pages: 336,
    description: "Jurnalul unei adolescente evreice ascunse în timpul ocupației naziste.",
    coverImage: "https://via.placeholder.com/150x220?text=Jurnalul+Annei+Frank",
    rating: 4.8,
    availableCopies: 18
  },
  {
    id: 20,
    title: "Bel-Ami",
    author: "Guy de Maupassant",
    genre: "Clasic / Dramă",
    publisher: "Litera",
    publicationYear: 1885,
    isbn: "9789736752370",
    language: "Română",
    pages: 320,
    description: "Roman despre ascensiunea socială și manipularea în societatea pariziană.",
    coverImage: "https://via.placeholder.com/150x220?text=Bel-Ami",
    rating: 4.4,
    availableCopies: 10
  },
  {
    id: 21,
    title: "Hamlet",
    author: "William Shakespeare",
    genre: "Dramă / Tragedie",
    publisher: "Humanitas",
    publicationYear: 1603,
    isbn: "9789735062500",
    language: "Română",
    pages: 200,
    description: "Tragedia prințului danez care caută răzbunare pentru moartea tatălui său.",
    coverImage: "https://via.placeholder.com/150x220?text=Hamlet",
    rating: 4.7,
    availableCopies: 12
  },
  {
    id: 22,
    title: "O mie nouă sute optzeci și patru",
    author: "George Orwell",
    genre: "Distopie",
    publisher: "Polirom",
    publicationYear: 1949,
    isbn: "9789734617992",
    language: "Română",
    pages: 328,
    description: "Un roman despre supraveghere, libertate și totalitarism.",
    coverImage: "https://via.placeholder.com/150x220?text=1984",
    rating: 4.8,
    availableCopies: 14
  },
  {
    id: 23,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Distopie / SF",
    publisher: "Polirom",
    publicationYear: 1953,
    isbn: "9789734607002",
    language: "Română",
    pages: 249,
    description: "O societate în care cărțile sunt interzise și arse.",
    coverImage: "https://via.placeholder.com/150x220?text=Fahrenheit+451",
    rating: 4.6,
    availableCopies: 11
  },
  {
    id: 24,
    title: "Dracula",
    author: "Bram Stoker",
    genre: "Horror / Gothic",
    publisher: "Polirom",
    publicationYear: 1897,
    isbn: "9789734618301",
    language: "Română",
    pages: 418,
    description: "Roman clasic gotic despre vampirul conte Dracula.",
    coverImage: "https://via.placeholder.com/150x220?text=Dracula",
    rating: 4.7,
    availableCopies: 13
  },
  {
    id: 25,
    title: "Shining",
    author: "Stephen King",
    genre: "Horror / Thriller",
    publisher: "Editura Nemira",
    publicationYear: 1977,
    isbn: "9789733209500",
    language: "Română",
    pages: 447,
    description: "Un hotel bântuit și un scriitor prins într-o spirală a nebuniei.",
    coverImage: "https://via.placeholder.com/150x220?text=Shining",
    rating: 4.5,
    availableCopies: 10
  },
  {
    id: 26,
    title: "Cronicile din Narnia: Leul, Vrăjitoarea și Dulapul",
    author: "C.S. Lewis",
    genre: "Fantasy / Aventură",
    publisher: "Rao",
    publicationYear: 1950,
    isbn: "9789731033000",
    language: "Română",
    pages: 208,
    description: "Copiii Pevensie descoperă o lume magică printr-un dulap.",
    coverImage: "https://via.placeholder.com/150x220?text=Narnia+1",
    rating: 4.8,
    availableCopies: 15
  },
  {
    id: 27,
    title: "Percy Jackson și Hoțul Fulgerului",
    author: "Rick Riordan",
    genre: "Fantasy / Aventură",
    publisher: "Arthur",
    publicationYear: 2005,
    isbn: "9786067884006",
    language: "Română",
    pages: 384,
    description: "Primul volum din seria Percy Jackson, bazată pe mitologia greacă.",
    coverImage: "https://via.placeholder.com/150x220?text=Percy+Jackson+1",
    rating: 4.7,
    availableCopies: 18
  },
  {
    id: 28,
    title: "Cei cinci detectivi",
    author: "Enid Blyton",
    genre: "Aventură / Copii",
    publisher: "Rao",
    publicationYear: 1942,
    isbn: "9789731032040",
    language: "Română",
    pages: 192,
    description: "O serie de aventuri ale copiilor detectivi.",
    coverImage: "https://via.placeholder.com/150x220?text=Cei+cinci+detectivi",
    rating: 4.4,
    availableCopies: 14
  },
  {
    id: 29,
    title: "Alice în Țara Oglinzilor",
    author: "Lewis Carroll",
    genre: "Fantezie / Aventură",
    publisher: "Rao",
    publicationYear: 1871,
    isbn: "9789731035000",
    language: "Română",
    pages: 208,
    description: "Continuarea aventurilor lui Alice într-o lume stranie și fascinantă.",
    coverImage: "https://via.placeholder.com/150x220?text=Alice+in+Tara+Oglinzilor",
    rating: 4.5,
    availableCopies: 12
  },
  {
    id: 30,
    title: "Viața lui Pi",
    author: "Yann Martel",
    genre: "Ficțiune / Aventură",
    publisher: "Polirom",
    publicationYear: 2001,
    isbn: "9789734614358",
    language: "Română",
    pages: 400,
    description: "Povestea unui băiat prins pe o barcă cu un tigru în mijlocul oceanului.",
    coverImage: "https://via.placeholder.com/150x220?text=Viata+lui+Pi",
    rating: 4.7,
    availableCopies: 16
  }
];

const app = express()
app.use(cors());


app.get('/', (req, res) => {
    console.log('CAlled endpoint');
  res.send(books);
});


app.listen(3000, () => {
    console.log('App started on port 3000');
});